// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace DigitalHealth.StoreAndForward.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Document list model.
    /// </summary>
    public partial class DocumentListModel
    {
        /// <summary>
        /// Initializes a new instance of the DocumentListModel class.
        /// </summary>
        public DocumentListModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DocumentListModel class.
        /// </summary>
        /// <param name="documents">Document list.</param>
        public DocumentListModel(IList<DocumentReferenceModel> documents = default(IList<DocumentReferenceModel>))
        {
            Documents = documents;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets document list.
        /// </summary>
        [JsonProperty(PropertyName = "documents")]
        public IList<DocumentReferenceModel> Documents { get; set; }

    }
}
