// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace DigitalHealth.StoreAndForward.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Event model.
    /// </summary>
    public partial class EventModel
    {
        /// <summary>
        /// Initializes a new instance of the EventModel class.
        /// </summary>
        public EventModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the EventModel class.
        /// </summary>
        /// <param name="id">Event ID.</param>
        /// <param name="eventDateTime">Event date time.</param>
        /// <param name="details">Event details.</param>
        /// <param name="type">Event type.</param>
        /// <param name="documentLink">Document link.</param>
        public EventModel(int? id = default(int?), System.DateTime? eventDateTime = default(System.DateTime?), string details = default(string), string type = default(string), string documentLink = default(string))
        {
            Id = id;
            EventDateTime = eventDateTime;
            Details = details;
            Type = type;
            DocumentLink = documentLink;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets event ID.
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// Gets or sets event date time.
        /// </summary>
        [JsonProperty(PropertyName = "event_date_time")]
        public System.DateTime? EventDateTime { get; set; }

        /// <summary>
        /// Gets or sets event details.
        /// </summary>
        [JsonProperty(PropertyName = "details")]
        public string Details { get; set; }

        /// <summary>
        /// Gets or sets event type.
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// Gets or sets document link.
        /// </summary>
        [JsonProperty(PropertyName = "document_link")]
        public string DocumentLink { get; set; }

    }
}
