// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace DigitalHealth.StoreAndForward.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Event list model.
    /// </summary>
    public partial class EventListModel
    {
        /// <summary>
        /// Initializes a new instance of the EventListModel class.
        /// </summary>
        public EventListModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the EventListModel class.
        /// </summary>
        /// <param name="events">Events.</param>
        public EventListModel(IList<EventModel> events = default(IList<EventModel>))
        {
            Events = events;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets events.
        /// </summary>
        [JsonProperty(PropertyName = "events")]
        public IList<EventModel> Events { get; set; }

    }
}
