/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import { RequestOptionsBase } from "ms-rest-js";


/**
 * @interface
 * An interface representing DocumentReferenceModel.
 */
export interface DocumentReferenceModel {
  /**
   * @member {number} [id]
   */
  id?: number;
  /**
   * @member {string} [documentId]
   */
  documentId?: string;
  /**
   * @member {string} [replaceId]
   */
  replaceId?: string;
  /**
   * @member {Date} [queueDateTime]
   */
  queueDateTime?: Date;
  /**
   * @member {string} [status]
   */
  status?: string;
  /**
   * @member {string} [documentLink]
   */
  documentLink?: string;
  /**
   * @member {string} [eventsLink]
   */
  eventsLink?: string;
  /**
   * @member {string} [formatCode]
   */
  formatCode?: string;
  /**
   * @member {string} [formatCodeName]
   */
  formatCodeName?: string;
  /**
   * @member {string} [ihi]
   */
  ihi?: string;
}

/**
 * @interface
 * An interface representing DocumentListModel.
 */
export interface DocumentListModel {
  /**
   * @member {DocumentReferenceModel[]} [documents]
   */
  documents?: DocumentReferenceModel[];
}

/**
 * @interface
 * An interface representing DocumentModel.
 */
export interface DocumentModel {
  /**
   * @member {Buffer} [data]
   */
  data?: Buffer;
  /**
   * @member {number} [id]
   */
  id?: number;
  /**
   * @member {string} [documentId]
   */
  documentId?: string;
  /**
   * @member {string} [replaceId]
   */
  replaceId?: string;
  /**
   * @member {Date} [queueDateTime]
   */
  queueDateTime?: Date;
  /**
   * @member {string} [status]
   */
  status?: string;
  /**
   * @member {string} [documentLink]
   */
  documentLink?: string;
  /**
   * @member {string} [eventsLink]
   */
  eventsLink?: string;
  /**
   * @member {string} [formatCode]
   */
  formatCode?: string;
  /**
   * @member {string} [formatCodeName]
   */
  formatCodeName?: string;
  /**
   * @member {string} [ihi]
   */
  ihi?: string;
}

/**
 * @interface
 * An interface representing EventModel.
 */
export interface EventModel {
  /**
   * @member {number} [id]
   */
  id?: number;
  /**
   * @member {Date} [eventDateTime]
   */
  eventDateTime?: Date;
  /**
   * @member {string} [details]
   */
  details?: string;
  /**
   * @member {string} [type]
   */
  type?: string;
  /**
   * @member {string} [documentLink]
   */
  documentLink?: string;
}

/**
 * @interface
 * An interface representing EventListModel.
 */
export interface EventListModel {
  /**
   * @member {EventModel[]} [events]
   */
  events?: EventModel[];
}

/**
 * @interface
 * An interface representing StoreAndForwardGetDocumentsOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface StoreAndForwardGetDocumentsOptionalParams extends RequestOptionsBase {
  /**
   * @member {Date} [startDate] Filter start date
   */
  startDate?: Date;
  /**
   * @member {Date} [endDate] Filter end date
   */
  endDate?: Date;
  /**
   * @member {string} [documentStatus] Filter status
   */
  documentStatus?: string;
  /**
   * @member {number} [offset] Page offset
   */
  offset?: number;
  /**
   * @member {number} [limit] Page limit
   */
  limit?: number;
}

/**
 * @interface
 * An interface representing StoreAndForwardGetEventsOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface StoreAndForwardGetEventsOptionalParams extends RequestOptionsBase {
  /**
   * @member {Date} [startDate] Filter start date
   */
  startDate?: Date;
  /**
   * @member {Date} [endDate] Filter end date
   */
  endDate?: Date;
  /**
   * @member {string} [eventType]
   */
  eventType?: string;
  /**
   * @member {number} [offset] Page offset
   */
  offset?: number;
  /**
   * @member {number} [limit] Page limit
   */
  limit?: number;
}
