/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */


export const DocumentReferenceModel = {
  required: false,
  serializedName: 'DocumentReferenceModel',
  type: {
    name: 'Composite',
    className: 'DocumentReferenceModel',
    modelProperties: {
      id: {
        required: false,
        serializedName: 'id',
        type: {
          name: 'Number'
        }
      },
      documentId: {
        required: false,
        serializedName: 'document_id',
        type: {
          name: 'String'
        }
      },
      replaceId: {
        required: false,
        serializedName: 'replace_id',
        type: {
          name: 'String'
        }
      },
      queueDateTime: {
        required: false,
        serializedName: 'queue_date_time',
        type: {
          name: 'DateTime'
        }
      },
      status: {
        required: false,
        serializedName: 'status',
        type: {
          name: 'String'
        }
      },
      documentLink: {
        required: false,
        serializedName: 'document_link',
        type: {
          name: 'String'
        }
      },
      eventsLink: {
        required: false,
        serializedName: 'events_link',
        type: {
          name: 'String'
        }
      },
      formatCode: {
        required: false,
        serializedName: 'format_code',
        type: {
          name: 'String'
        }
      },
      formatCodeName: {
        required: false,
        serializedName: 'format_code_name',
        type: {
          name: 'String'
        }
      },
      ihi: {
        required: false,
        serializedName: 'ihi',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const DocumentListModel = {
  required: false,
  serializedName: 'DocumentListModel',
  type: {
    name: 'Composite',
    className: 'DocumentListModel',
    modelProperties: {
      documents: {
        required: false,
        serializedName: 'documents',
        type: {
          name: 'Sequence',
          element: {
              required: false,
              serializedName: 'DocumentReferenceModelElementType',
              type: {
                name: 'Composite',
                className: 'DocumentReferenceModel'
              }
          }
        }
      }
    }
  }
};

export const DocumentModel = {
  required: false,
  serializedName: 'DocumentModel',
  type: {
    name: 'Composite',
    className: 'DocumentModel',
    modelProperties: {
      data: {
        required: false,
        serializedName: 'data',
        type: {
          name: 'ByteArray'
        }
      },
      id: {
        required: false,
        serializedName: 'id',
        type: {
          name: 'Number'
        }
      },
      documentId: {
        required: false,
        serializedName: 'document_id',
        type: {
          name: 'String'
        }
      },
      replaceId: {
        required: false,
        serializedName: 'replace_id',
        type: {
          name: 'String'
        }
      },
      queueDateTime: {
        required: false,
        serializedName: 'queue_date_time',
        type: {
          name: 'DateTime'
        }
      },
      status: {
        required: false,
        serializedName: 'status',
        type: {
          name: 'String'
        }
      },
      documentLink: {
        required: false,
        serializedName: 'document_link',
        type: {
          name: 'String'
        }
      },
      eventsLink: {
        required: false,
        serializedName: 'events_link',
        type: {
          name: 'String'
        }
      },
      formatCode: {
        required: false,
        serializedName: 'format_code',
        type: {
          name: 'String'
        }
      },
      formatCodeName: {
        required: false,
        serializedName: 'format_code_name',
        type: {
          name: 'String'
        }
      },
      ihi: {
        required: false,
        serializedName: 'ihi',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const EventModel = {
  required: false,
  serializedName: 'EventModel',
  type: {
    name: 'Composite',
    className: 'EventModel',
    modelProperties: {
      id: {
        required: false,
        serializedName: 'id',
        type: {
          name: 'Number'
        }
      },
      eventDateTime: {
        required: false,
        serializedName: 'event_date_time',
        type: {
          name: 'DateTime'
        }
      },
      details: {
        required: false,
        serializedName: 'details',
        type: {
          name: 'String'
        }
      },
      type: {
        required: false,
        serializedName: 'type',
        type: {
          name: 'String'
        }
      },
      documentLink: {
        required: false,
        serializedName: 'document_link',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const EventListModel = {
  required: false,
  serializedName: 'EventListModel',
  type: {
    name: 'Composite',
    className: 'EventListModel',
    modelProperties: {
      events: {
        required: false,
        serializedName: 'events',
        type: {
          name: 'Sequence',
          element: {
              required: false,
              serializedName: 'EventModelElementType',
              type: {
                name: 'Composite',
                className: 'EventModel'
              }
          }
        }
      }
    }
  }
};

export const StoreAndForwardGetDocumentsOptionalParams = {
  required: false,
  serializedName: 'GetDocumentsOptions',
  type: {
    name: 'Composite',
    className: 'StoreAndForwardGetDocumentsOptionalParams',
    modelProperties: {
      startDate: {
        required: false,
        serializedName: 'start_date',
        type: {
          name: 'DateTime'
        }
      },
      endDate: {
        required: false,
        serializedName: 'end_date',
        type: {
          name: 'DateTime'
        }
      },
      documentStatus: {
        required: false,
        serializedName: 'document_status',
        type: {
          name: 'String'
        }
      },
      offset: {
        required: false,
        serializedName: 'offset',
        type: {
          name: 'Number'
        }
      },
      limit: {
        required: false,
        serializedName: 'limit',
        type: {
          name: 'Number'
        }
      }
    }
  }
};

export const StoreAndForwardGetEventsOptionalParams = {
  required: false,
  serializedName: 'GetEventsOptions',
  type: {
    name: 'Composite',
    className: 'StoreAndForwardGetEventsOptionalParams',
    modelProperties: {
      startDate: {
        required: false,
        serializedName: 'start_date',
        type: {
          name: 'DateTime'
        }
      },
      endDate: {
        required: false,
        serializedName: 'end_date',
        type: {
          name: 'DateTime'
        }
      },
      eventType: {
        required: false,
        serializedName: 'event_type',
        type: {
          name: 'String'
        }
      },
      offset: {
        required: false,
        serializedName: 'offset',
        type: {
          name: 'Number'
        }
      },
      limit: {
        required: false,
        serializedName: 'limit',
        type: {
          name: 'Number'
        }
      }
    }
  }
};
